spring:
  application:
    name: gestao-portifolio
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/desafio_portfolio}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:senha}
  jpa:
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQL95Dialect
    # mvc:
    #   pathmatch:
    #     matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG
    org.springframework: INFO